apiVersion: apps/v1
kind: Deployment
metadata:
  name: resume-mcp
  namespace: resume
  labels:
    app: resume-mcp
    version: v1
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      app: resume-mcp
  template:
    metadata:
      labels:
        app: resume-mcp
        version: v1
    spec:
      containers:
        - name: resume-mcp
          image: ghcr.io/rxtech-lab/resume-mcp:latest
          ports:
            - containerPort: 8080
              protocol: TCP
          env:
            - name: PORT
              value: "8080"
            - name: BASE_URL
              value: https://resume.mcprouter.app
          envFrom:
            - secretRef:
                name: resume-mcp-secrets
          resources:
            requests:
              memory: "128Mi"
              cpu: "250m"
            limits:
              memory: "256Mi"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 5
            failureThreshold: 3
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            runAsUser: 1001
            runAsGroup: 1001
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
      securityContext:
        fsGroup: 1001
      restartPolicy: Always
